name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? Who benefits?
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Any sketches, references, or alternatives considered

